//------------------------------------------------------------------------------
// <auto-generated>
// This class was auto generated by the AI Name Map Generator
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apex.AI
{
    using System;

    public static class AINameMap
    {
		public static readonly Guid CellScanner = new Guid("a7f9c39f-e205-45fe-abcc-d669a12c3dbd");
		public static readonly Guid CompanionUtilityAI = new Guid("15f5c4bf-a00f-4642-bb5d-ce4a3f13807b");

    }
}
